name: my_btcz_wallet
description: "BitcoinZ SPV Wallet - A secure, lightweight cryptocurrency wallet"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  provider: ^6.1.1
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^8.0.3
  
  # Storage
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  
  # Networking
  dio: ^5.8.0
  ssl_pinning_plugin: ^2.0.0
  connectivity_plus: ^6.1.3
  
  # Cryptography
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  crypto: ^3.0.3
  bs58check: ^1.0.2
  pointycastle: ^3.9.1
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^6.0.6
  
  # Utilities
  logger: ^2.5.0
  intl: ^0.20.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
